# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
# Default database config with PostgreSQL
default: &default
  adapter: postgresql
  host: 127.0.0.1
  encoding: utf8
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: reinier
  password: ''
  timeout: 5000

development:
  <<: *default
  # To use it directly from
  database: reiniergarcia_website_development

test:
  <<: *default
  # To use it directly from
  database: reiniergarcia_website_test
  min_messages: WARNING

production:
  #  <<: *default
  # To use it directly from
  database: reiniergarcia_website_production
  port: 5432